### ISSUE TITLE
feat: TL;DR implementation

### ISSUE THREAD

**Issue by hemanialaparthi** [GatorEducator/gatorgrade#144]
Description:  GatorGrader includes many commands, but many students, especially in introductory classes, are unfamiliar with most of them. To make it easier for students to understand and use GatorGrader, a `--tldr` option would be a helpful addition.

Solution: 

The `--tldr` flag will offer two main features:

- Running `--tldr` alone will display a summary of commonly used GatorGrader commands with example usage.
- Running `--tldr [specific command]` will provide a detailed explanation and example for the specified command.

This addition will make GatorGrader more accessible to new users by offering quick reference information in a simplified format.

**Comment by gkapfham** [comment]
Hello @hemanialaparthi it is also important to point out that many _teachers_ who use GatorGrade as the front end for GatorGrader do now know the commands for using the tool, especially when it comes to writing the `gatorgrade.yml` file.

Here is an example:

```
- description: Ensure that Question 1 has correct number of documented functions using the command 'symbex'
  check: MatchCommandFragment
  options:
    command: "poetry run symbex -s --documented -f questions/question_one.py --count"
    fragment: 3
    count: 1
    exact: true
```

It would be nice if the `--tldr` actually gave examples of all of the various commands, like `MatchCommandFragment` that can be specified for running in a `gatorgrade.yml` file.
