### ISSUE TITLE
`gatorgrade.yml` format

### ISSUE THREAD

**Issue by mariakimheinert** [GatorEducator/gatorgrade#42]
Here is what a `gatorgrade.yml` file should look like. GatorGrade should be able to parse this file and run all of the GatorGrader/command checks defined in the file. Additionally, the `gatorgrade generate` command should generate a file that conforms to the same format.

```yml
setup: |
  ./script.sh
  poetry install
  echo "Setup Complete!"
---
- path/to:
  - file.py:
    - description: Complete all TODOs
      check: MatchFileFragment
      options:
        fragment: TODO
        count: 0
        exact: true
    - description: Use an if statement
      check: MatchFileRegex
      options:
        regex: "if .*?:"
        count: 1
        exact: false
  - file2.py:
    - description: Complete all TODOs
      check: MatchFileFragment
      options:
        fragment: TODO
        count: 0
        exact: true
- description: Pass MDL
  command: mdl .
- description: Pass HTMLHint
  command: htmlhint
- description: Have a total of 8 commits, 5 of which were created by you
  check: CountCommits
  options:
    count: 8
```
